// Calibration: fitting the shooter's physics to measured test shots.
const test = require("node:test");
const assert = require("node:assert/strict");
const { engine, defaultParams } = require("./helpers.cjs");

// Test shots a team would take: a spread of hood angles and speeds, measured on the floor or a wall.
const SHOTS = [
  { hood: 35, rpm: 2600, kind: "floor" }, { hood: 45, rpm: 2600, kind: "floor" },
  { hood: 55, rpm: 3000, kind: "floor" }, { hood: 40, rpm: 3400, kind: "wall", dist: 60 },
  { hood: 50, rpm: 3800, kind: "wall", dist: 90 }, { hood: 30, rpm: 3200, kind: "floor" },
];
const TRUTH = { eff: 76, cd: 0.62, magnus: 0.7 };

// Measurements generated by the model itself from known physics (optionally with a hood offset and noise).
function measure(truth, hoodOffset = 0, noise = () => 0) {
  const P = defaultParams(truth);
  return SHOTS.map(s => ({ ...s, measured: engine.predictShot(P, { ...s, hood: s.hood + hoodOffset }) + noise() }));
}

test("predictions: more rpm lands farther; a wall at the landing spot is hit at ball-radius height", () => {
  const P = defaultParams();
  const near = engine.predictShot(P, { hood: 45, rpm: 2400, kind: "floor" });
  const far = engine.predictShot(P, { hood: 45, rpm: 3200, kind: "floor" });
  assert.ok(far > near + 10, `${near} → ${far}`);
  const atLanding = engine.predictShot(P, { hood: 45, rpm: 3200, kind: "wall", dist: far });
  assert.ok(Math.abs(atLanding - P.ballD / 2) < 0.05, `wall height ${atLanding} at the landing distance`);
});

test("fitting exact measurements recovers efficiency, drag and lift", () => {
  const fit = engine.calibrate(defaultParams(), measure(TRUTH), ["eff", "cd", "magnus"]);
  assert.ok(Math.abs(fit.values.eff - TRUTH.eff) < 1, `eff ${fit.values.eff}`);
  assert.ok(Math.abs(fit.values.cd - TRUTH.cd) < 0.05, `cd ${fit.values.cd}`);
  assert.ok(fit.rms < 0.1, `rms ${fit.rms} in`);
});

test("a hood that reads 3° low is found as a +3° offset", () => {
  const fit = engine.calibrate(defaultParams(), measure(TRUTH, 3), ["eff", "cd", "magnus", "hoodOffset"]);
  assert.ok(Math.abs(fit.values.hoodOffset - 3) < 0.4, `offset ${fit.values.hoodOffset}`);
  assert.ok(Math.abs(fit.values.eff - TRUTH.eff) < 2, `eff ${fit.values.eff}`);
});

test("half-inch measurement noise still lands close", () => {
  let seed = 7;
  const rand = () => { seed = (seed * 16807) % 2147483647; return (seed / 2147483647 - 0.5); };
  const fit = engine.calibrate(defaultParams(), measure(TRUTH, 0, () => rand()), ["eff", "cd", "magnus"]);
  assert.ok(Math.abs(fit.values.eff - TRUTH.eff) < 3, `eff ${fit.values.eff}`);
  assert.ok(fit.rms < 0.6, `rms ${fit.rms}`);
  assert.equal(fit.residuals.length, SHOTS.length);
});
